### ISSUE TITLE
passive message box

### ISSUE THREAD

**Issue by jrfrun** [SciViews/svDialogs#8]
I have been very happy with the svDialogs package and I use it regularly.  But currently I have been looking for a passive message box (such as work in progress) which is activated within the code and does not allow the user to answer, but code works behind the scene until is done and removed with internal code after the code is completely executed.

I call this a passive message (not requiring a response from user.  This might be modal thing, not sure

I did not see this capability within the documentation but I might have missed it

any help would be welcomed

**Comment by phgrosjean** [comment]
The way svDialogs is programmed does not allow this because the R event loop is interrupted while de dialog box is displayed by design (the goal is to interrupt computations and let the user to interact with the dialog box before continuing computations).
You should look at {tcltk} for a dialog box to do that. By the way, it is called non modal dialog box.
